server:
  port: 8082

spring:
  application:
    name: SignupService

  datasource:
    url: jdbc:postgresql://localhost:5432/CustomerCom
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # or validate / create / none based on your need
    show-sql: true
    properties:
      hibernate:
        format_sql: true
